import numpy as np

rename_cols = {
    "Geschlecht": "Gender",
    "Altersgruppe": "Age",
    "Höchster Bildungsabschluss": "Education",
    "Beruf": "Occupation",
    "Bundesland": "State",
    "Der Klimawandel findet tatsächlich statt.": "Climate Change 1",
    "Der Klimawandel ist ein ernstes Problem.": "Climate Change 2",
    "Menschliche Aktivitäten sind die Hauptursache des Klimawandels.": "Climate Change 3",
    "Wir alle sollten uns bemühen, unseren CO2-Ausstoß zu reduzieren.": "Climate Change 4",
    "Haben Sie schon von Technologien zur Entnahme von Kohlendioxid (CO2) aus der Luft (auf Englisch Direct Air Capture (DAC)) gehört?": "DAC Awareness",
    "Wie gut sind ihre Kenntnisse dieser Technologien?": "DAC Knowledge",
    "Haben Sie schon von Kohlendioxid (CO2)-Speicherung gehört?": "Storage Awareness",
    "Wie gut sind ihre Kenntnisse der CO2-Speicherungstechnologien?": "Storage Knowledge",
    "Direct Air Capture (DAC)": "Initial DAC Support",  # TWO COLUMNS ARE NAMED THE SAME!!!! this one is considering the final support
    "CO2-Speicherung": "Initial Storage Support",
    "Welche Hauptemotion empfinden Sie gegenüber DAC-Technologien?": "First Emotion",
    "DAC ist eine ausgereifte saubere Technologie.": "Maturity",
    "Menschen sollten die Natur nicht auf diese Weise manipulieren.": "Tampering 1",
    "Ich denke nicht, dass das Einbringen von CO2 in den Boden eine gute Idee ist.": "Tampering 2",
    "Versuche, das Klimasystem durch die Anwendung von DAC zu beeinflussen, zeugen von menschlichem Hochmut.": "Tampering 3",
    "DAC Anlage": "NIMBY 1",
    "CO2-Speicherung im Boden": "NIMBY 2",
    "CO2-Speicherung im Meeresboden": "NIMBY 3",
    "LKW": "Transport 1",
    "Eisenbahn": "Transport 2",
    "Pipeline (Rohrleitungstransport)": "Transport 3",
    "Tanker (Schiff)": "Transport 4",
    "Mit keiner": "Transport 5",
    "Weiß nicht": "Transport 6",
    "Emissionen zu reduzieren wäre kosteneffizienter als DAC.": "Cost 1",
    "100 € für die Entnahme von 1 Tonne CO2 zu zahlen, ist ein angemessener Preis.": "Cost 2",
    "DAC könnte dazu beitragen, schwer vermeidbare Emissionen aus Sektoren wie Landwirtschaft oder Zementproduktion zu entnehmen.": "Benefit 1",
    "Die Implementierung von DAC als Teil einer Gesamtstrategie kann Deutschland dabei helfen, seine Klimaziele zu erreichen und den Klimawandel auf 1,5 °C zu begrenzen.": "Benefit 2",
    "DAC ist eine effiziente Technologie zur Bekämpfung des Klimawandels.": "Benefit 3",
    "DAC ist sicher.": "Safety 1",
    "CO2-Speicherung ist sicher.": "Safety 2",
    "CO2-Speicherung könnte Erdbeben verursachen.": "Risk 1",
    "CO2-Speicherung könnte Explosionen verursachen.": "Risk 2",
    "CO2-Speicherung könnte CO2-Leckagen verursachen.": "Risk 3",
    "Politik": "Trust 1",
    "Industrie": "Trust 2",
    "Wissenschaft": "Trust 3",
    "Vereinte Nationen (UNO)": "Trust 4",
    "Europäische Union": "Trust 5",
    "Nichtregierungs- und  Umweltschutzorganisationen": "Trust 6",
    "Medien": "Trust 7",
    "Direct Air Capture (DAC).1": "Final DAC Support",
    # One more needed for the final DAC support currently an error
    "CO2-Speicherung.1": "Final Storage Support",
    "Ihre E-Mail Adresse": "Engagement",
}


replacer = {
    "Überhaupt nicht": 1,
    "Eher nicht": 2,
    "Neutral": 3,
    "Etwas": 4,
    "Voll und ganz": 5,
    "Nein": 1,
    "Nur gehört / Keine Kenntnisse ": 2,
    "Nur gehört / Keine Kenntnisse": 2,
    "Grundverständnis": 3,
    "Gute Kenntnisse": 4,
    "Sehr gute Kenntnisse": 5,
    "Stimme überhaupt nicht zu": 1,
    "Stimme nicht zu": 2,
    "Stimme weder zu noch lehne ich ab": 3,
    "Stimme zu": 4,
    "Stimme ich zu": 4,
    "Stimme voll und ganz zu": 5,
    "Weiß nicht": np.nan,
    "Männlich": 1,
    "Weiblich": 2,
    "Divers": 3,
    "18-19": 1,
    "20 - 29": 2,
    "30 - 39": 3,
    "40 - 49": 4,
    "50 - 59": 5,
    "60+": 6,
    "(noch) kein Abschluss": 1,
    "Volks-/Hauptschule": 2,
    "Weiterführende Schule ohne Abitur": 3,
    "Ausbildung": 4,
    "Abitur/(Fach-)Hochschulreife": 5,
    "Bachelor (BSc.)": 6,
    "Master (MSc.) oder Diplom": 7,
    "Promotion (Dr.) oder Habilitation (Prof.)": 8,
    "Studierende": 1,
    "Angestellt": 2,
    "Selbständig": 3,
    "Öffentlicher Dienst": 4,
    "Arbeitsuchend": 5,
    "im Ruhestand": 6,
    "Baden-Württemberg": 1,
    "Bayern": 2,
    "Berlin": 3,
    "Brandenburg": 4,
    "Bremen": 5,
    "Hamburg": 6,
    "Hessen": 7,
    "Mecklenburg-Vorpommern": 8,
    "Niedersachsen": 9,
    "Nordrhein-Westfalen": 10,
    "Rheinland-Pfalz": 11,
    "Saarland": 12,
    "Sachsen": 13,
    "Sachsen-Anhalt": 14,
    "Schleswig-Holstein": 15,
    "Thüringen": 16,
    "Ich lebe im Ausland": 17,
    "Hoffnung": 1,
    "Begeisterung": 1,
    "Glück": 1,  # SHOULD WE LEAVE THIS BINARY OR IN 1 TO 6?
    "Wut": 2,
    "Sorge": 2,
    "Angst": 2,
    "Nirgendwo in Deutschland": 5,
    "100 km": 4,
    "10 km": 3,
    "1 km": 2,
    "500 m": 1,
    "Überhaupt kein Vertrauen": 1,
    "Geringes Vertrauen ": 2,
    "Mäßiges Vertrauen ": 4,
    "Starkes Vertrauen": 5,
}


drop_cols = [
    "Language",
    "IP address",
    "Device",
    "Status",
    "Collector",
    "Sind Sie einverstanden?",
    "Bitte bewerten Sie die folgenden Aussagen über den Klimawandel.",
    "Unterstützen Sie die Einführung der folgenden Technologien?",
    "Bitte bewerten Sie die folgenden Aussagen über die DAC-Technologien.",
    "Wenn die folgenden Technologien in Deutschland eingeführt wären, wie groß sollte der Mindestabstand zur nächsten Siedlung sein?",
    "Mit welchen CO2-Transportwege wären Sie einverstanden?",
    "Inwiefern stimmen Sie den folgenden Aussagen zu?",
    "Inwiefern vertrauen Sie darauf, dass diese Gruppen im Interesse der Gesellschaft handeln werden?",
    "Unterstützen Sie die Einführung der folgenden Technologien?.1",
]
